error_on_line_overflow = true
error_on_unformatted = true
max_width = 400
chain_width = 60
array_width = 60
comment_width = 80
fn_call_width = 60
struct_lit_width = 18
attr_fn_like_width = 70
struct_variant_width = 35
inline_attribute_width = 0
single_line_if_else_max_width = 50
